name: PR Check

on:
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '8.0.412'

jobs:
  format-check:
    name: Check Formatting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dotnet-format
      run: dotnet tool install --global dotnet-format
    
    - name: Check formatting
      run: dotnet format --verify-no-changes --verbosity diagnostic
    
    - name: Check for trailing whitespace
      run: |
        # Check for trailing whitespace in .cs files
        if grep -r --include="*.cs" --include="*.csproj" --include="*.props" --include="*.xml" " $" .; then
          echo "Error: Found trailing whitespace in files"
          exit 1
        fi
    
    - name: Check for mixed line endings
      run: |
        # Check for mixed line endings
        if grep -r --include="*.cs" --include="*.csproj" --include="*.props" --include="*.xml" -U $'\r\n' .; then
          echo "Error: Found mixed line endings (CRLF) in files"
          exit 1
        fi

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install StyleCop.Analyzers
      run: |
        dotnet tool install --global dotnet-format
        dotnet tool install --global Microsoft.CodeAnalysis.NetAnalyzers
    
    - name: Run analyzers
      run: |
        dotnet build --configuration Release --verbosity normal
        dotnet format --verify-no-changes --verbosity diagnostic
    
    - name: Check for compiler warnings
      run: |
        # Build and capture warnings
        dotnet build --configuration Release --verbosity normal 2>&1 | tee build.log
        
        # Check if there are any warnings (excluding known acceptable warnings)
        if grep -i "warning" build.log | grep -v "NU1605\|NU1701\|CS8618\|CS8600\|CS8601\|CS8602\|CS8603\|CS8604\|CS8619"; then
          echo "Error: Found compiler warnings"
          cat build.log
          exit 1
        fi

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Check for outdated packages
      run: |
        dotnet tool install --global dotnet-outdated-tool
        dotnet outdated --fail-on-updates
    
    - name: Check for vulnerable packages
      run: |
        dotnet list package --vulnerable
        
        # Fail if vulnerabilities are found
        if dotnet list package --vulnerable | grep -q "vulnerable"; then
          echo "Error: Found vulnerable packages"
          dotnet list package --vulnerable
          exit 1
        fi

  test-coverage:
    name: Test Coverage Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install coverlet.collector
      run: dotnet tool install --global coverlet.collector
    
    - name: Run tests with coverage
      run: |
        dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage/ --verbosity normal
    
    - name: Generate coverage report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:./coverage/**/coverage.cobertura.xml -targetdir:./coverage-report -reporttypes:Html
    
    - name: Check coverage threshold
      run: |
        # Extract coverage percentage (simplified check)
        coverage=$(find ./coverage -name "coverage.cobertura.xml" -exec grep -o 'line-rate="[^"]*"' {} \; | head -1 | cut -d'"' -f2)
        coverage_percent=$(echo "$coverage * 100" | bc -l)
        
        echo "Code coverage: ${coverage_percent}%"
        
        # Fail if coverage is below 80%
        if (( $(echo "$coverage_percent < 80" | bc -l) )); then
          echo "Error: Code coverage is below 80%"
          exit 1
        fi
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-pr
        path: ./coverage-report/
        retention-days: 7 