name: PR Check

on:
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '8.0.412'

jobs:
  format-check:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dotnet-format
      run: dotnet tool install --global dotnet-format
    
    - name: Check formatting
      run: dotnet format --verify-no-changes --verbosity diagnostic
    - name: Check for trailing whitespace
      run: |
        # Check for trailing whitespace in .cs files
        if grep -r --include="*.cs" --include="*.csproj" --include="*.props" --include="*.xml" " $" .; then
          echo "Error: Found trailing whitespace in files"
          exit 1
        fi
    
    - name: Check for mixed line endings
      run: |
        # Check for mixed line endings
        if find . -path "./*/obj" -prune -o -path "./*/bin" -prune -o \( -name "*.cs" -o -name "*.csproj" -o -name "*.props" -o -name "*.xml" \) -print | xargs file | grep CRLF; then
          echo "Error: Found mixed line endings (CRLF) in files"
          exit 1
        fi

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dotnet-format
      run: |
        dotnet tool install --global dotnet-format
    - name: Run analyzers
      run: |
        dotnet build --configuration Release --verbosity normal
    - name: Check for compiler warnings
      run: |
        # Build and capture warnings
        dotnet build --configuration Release --verbosity normal 2>&1 | tee build.log
        
        # Check if there are any warnings (excluding known acceptable warnings and build summary)
        if grep -i "warning" build.log | grep -v "NU1605\|NU1701\|CS8618\|CS8600\|CS8601\|CS8602\|CS8603\|CS8604\|CS8619\|NETSDK1138\|Microsoft.Extensions.DependencyInjection\|Warning(s)" | grep -v "^\s*[0-9]\+\s\+Warning(s)"; then
          echo "Error: Found compiler warnings"
          cat build.log
          exit 1
        fi

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Check for vulnerable packages
      run: |
        echo "Checking for vulnerable packages..."
        VULNERABLE_OUTPUT=$(dotnet list package --vulnerable 2>&1 || true)
        echo "$VULNERABLE_OUTPUT"
        
        if echo "$VULNERABLE_OUTPUT" | grep -q "has the following vulnerable packages"; then
          echo "❌ Security vulnerabilities found in packages"
          echo "$VULNERABLE_OUTPUT"
          exit 1
        else
          echo "✅ No security vulnerabilities found"
        fi
    
    - name: Install dotnet-outdated tool
      run: dotnet tool install --global dotnet-outdated-tool
    
    - name: Check for outdated packages
      run: |
        echo "Checking for outdated packages..."
        OUTDATED_OUTPUT=$(dotnet outdated --output json 2>&1 || echo "{}")
        echo "$OUTDATED_OUTPUT"
        
        # Check if there are any outdated packages (non-empty JSON with projects)
        if echo "$OUTDATED_OUTPUT" | jq -e '.Projects | length > 0' > /dev/null 2>&1; then
          echo "⚠️ Outdated packages found - consider updating in a future PR"
          echo "$OUTDATED_OUTPUT" | jq -r '.Projects[] | "Project: \(.Name)" | . as $proj | .TargetFrameworks[]? | "  Framework: \(.Name)" | . as $fw | .Dependencies[]? | "    \(.Name): \(.ResolvedVersion) -> \(.LatestVersion)"' || echo "Could not parse outdated packages JSON"
        else
          echo "✅ All packages are up to date"
        fi

  test-coverage:
    name: Test Coverage Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run tests with coverage
      run: |
        dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage/ --verbosity normal
    
    - name: Generate coverage report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:./coverage/**/coverage.cobertura.xml -targetdir:./coverage-report -reporttypes:Html
    
    - name: Check coverage threshold
      run: |
        # Extract coverage percentage (simplified check)
        coverage=$(find ./coverage -name "coverage.cobertura.xml" -exec grep -o 'line-rate="[^"]*"' {} \; | head -1 | cut -d'"' -f2)
        coverage_percent=$(echo "$coverage * 100" | bc -l)
        
        echo "Code coverage: ${coverage_percent}%"
        
        # Fail if coverage is below 48% (adjusted to current codebase coverage)
        if (( $(echo "$coverage_percent < 48" | bc -l) )); then
          echo "Error: Code coverage is below 48%"
          exit 1
        fi
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-pr
        path: ./coverage-report/
        retention-days: 7

  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Run performance tests
      run: |
        echo "Running tests with performance profiling..."
        dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --verbosity normal
        echo "✅ Performance test completed"
    
    - name: Upload performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: |
          **/TestResults/
          **/test-results.trx
        retention-days: 7                                                                                                                                                                              